{ pkgs, package }:
pkgs.testers.runNixOSTest {
  name = "systemd_traefik_configuration_provider-e2e";

  nodes.machine = {
    systemd.services.systemd_traefik_configuration_provider = {
      wantedBy = [ "multi-user.target" ];
      environment = {
        TRAEFIK_OUT_DIR = "/var/lib/traefik-dynamic";
        RUST_LOG = "systemd_traefik_configuration_provider=debug";
      };
      serviceConfig.ExecStart = "${package}/bin/systemd_traefik_configuration_provider --log-hide-date";
    };
  };

  testScript = ''
    out = "/var/lib/traefik-dynamic"
    yml = f"{out}/web.service.yml"
    marker = "# Generated by systemd_traefik_configuration_provider, do not edit."

    def write(path, content):
        machine.succeed(f"mkdir -p $(dirname {path}) && cat > {path} <<'EOF'\n{content}\nEOF")

    def traefik_drop_in(name, host):
        write(
            f"/run/systemd/system/web.service.d/{name}.conf",
            f"[X-Traefik]\nLabel=traefik.http.routers.web.rule=Host(`{host}`)",
        )

    def reload():
        machine.succeed("systemctl daemon-reload")

    machine.wait_for_unit("systemd_traefik_configuration_provider.service")

    with subtest("a running unit with a Traefik drop-in gets a file"):
        write("/run/systemd/system/web.service", "[Service]\nExecStart=${pkgs.coreutils}/bin/sleep infinity")
        traefik_drop_in("10-traefik-a", "a.example")
        reload()
        machine.succeed("systemctl start web.service")
        machine.wait_until_succeeds(f"grep -F 'Host(`a.example`)' {yml}", timeout=30)
        machine.succeed(f"head -1 {yml} | grep -qxF '{marker}'")

    with subtest("a drop-in moved to a new path is read again on reload"):
        machine.succeed("rm /run/systemd/system/web.service.d/10-traefik-a.conf")
        traefik_drop_in("20-traefik-b", "b.example")
        reload()
        machine.wait_until_succeeds(f"grep -F 'Host(`b.example`)' {yml}", timeout=30)
        machine.fail(f"grep -F 'a.example' {yml}")

    with subtest("a unit that loses its Traefik config on reload loses its file"):
        machine.succeed("rm /run/systemd/system/web.service.d/20-traefik-b.conf")
        reload()
        machine.wait_until_fails(f"test -e {yml}", timeout=30)

    with subtest("a unit that gains Traefik config on reload gets its file"):
        traefik_drop_in("30-traefik-c", "c.example")
        reload()
        machine.wait_until_succeeds(f"grep -F 'Host(`c.example`)' {yml}", timeout=30)

    with subtest("stopping the unit removes its file"):
        machine.succeed("systemctl stop web.service")
        machine.wait_until_fails(f"test -e {yml}", timeout=30)

    with subtest("generated orphans are pruned on startup, other files are kept"):
        machine.succeed("systemctl stop systemd_traefik_configuration_provider.service")
        write(f"{out}/gone.service.yml", f"{marker}\nhttp: {{}}")
        write(f"{out}/handwritten.yml", "http: {}")
        machine.succeed("systemctl start systemd_traefik_configuration_provider.service")
        machine.wait_until_fails(f"test -e {out}/gone.service.yml", timeout=30)
        machine.succeed(f"test -e {out}/handwritten.yml")
  '';
}
