name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"
    paths-ignore:
      - "*.md"
      - "*.yaml"
      - .editorconfig
      - ".forgejo/**"
      - .gitignore
  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "*.yaml"
      - .editorconfig
      - ".forgejo/**"
      - .gitignore

env:
  CI_RUN: ${{ forgejo.server_url != '' && '1' || '' }}
jobs:
  build:
    name: cargo build
    runs-on: docker
    container:
      # derived from nixos/nix:2.32.8
      image: giggio/nixaction
    steps:
      - uses: actions/checkout@v4
      - name: Set user for Cachix
        run: echo "USER=root" >> $GITHUB_ENV
      - name: Set up cache
        uses: https://github.com/cachix/cachix-action.git@v15
        with:
          name: giggio
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: |
          echo -e 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf
          echo "Starting nix development environment..."
          nix print-dev-env . --verbose
        name: Configure nix
      - name: Build and test x86_64
        run: |
          source <(nix print-dev-env . --verbose)
          make target/tmp/systemd_traefik_configuration_provider_x86_64
      - name: Build and test aarch64
        run: |
          source <(nix print-dev-env . --verbose)
          make target/tmp/systemd_traefik_configuration_provider_aarch64
