name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"
    paths-ignore:
      - "*.md"
      - "*.yaml"
      - .editorconfig
      - ".forgejo/**"
      - .gitignore
  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "*.yaml"
      - .editorconfig
      - ".forgejo/**"
      - .gitignore
env:
  CI_RUN: ${{ forgejo.server_url != '' && '1' || '' }}
jobs:
  build:
    name: cargo build
    runs-on: docker
    container:
      # derived from nixos/nix:2.35.2
      image: giggio/nixaction
    steps:
      - uses: actions/checkout@v4
      - name: Set user for Cachix
        run: echo "USER=root" >> $GITHUB_ENV
      - name: Set up cache
        uses: https://github.com/cachix/cachix-action.git@v15
        with:
          name: giggio
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: |
          echo -e 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf
          echo "Starting nix development environment..."
          nix print-dev-env . --verbose
        name: Configure nix
      - name: Test and lint x86_64
        run: make check_nix
      - name: End-to-end test (emulated, no KVM)
        run: make e2e_no_kvm
      - name: Lint markdown
        run: make lint_md
      - name: Build x86_64
        run: make build_x86_64
      - name: Build aarch64
        run: make build_aarch64
