use anyhow::{Context, Result};
use std::{
    collections::HashSet,
    path::{Path, PathBuf},
    sync::Arc,
};

use crate::{
    dbus::{DBusContext, JobEvent, UnitData, UnitList},
    helpers::sanitize_filename,
    infra::FileSystem,
    yaml::build_traefik_file_yaml,
};

/// First line of every generated file. Only files carrying it are ever pruned, because the
/// output directory may be shared with other Traefik dynamic configuration.
const GENERATED_MARKER: &str =
    "# Generated by systemd_traefik_configuration_provider, do not edit.\n";

pub async fn reconcile(
    dbus: &DBusContext<'_>,
    watched_units: &UnitList,
    fs: &dyn FileSystem,
    traefik_dir: &Path,
) -> Result<()> {
    let units = watched_units
        .read()
        .await
        .iter()
        .map(|(unit_name, unit_data)| (unit_name.clone(), unit_data.clone()))
        .collect::<Vec<_>>();
    for (unit_name, unit_data) in units {
        let started = match dbus.is_unit_running(unit_name.clone()).await {
            Ok(running) => running,
            Err(e) => {
                error!("Error checking if unit {unit_name} is running: {e}");
                false
            }
        };
        debug!(
            "Reconciling unit {} as {}started",
            unit_name,
            if started { "" } else { "not " }
        );
        if let Err(e) =
            handle_service_state_changed(dbus, started, &unit_data, fs, traefik_dir).await
        {
            error!(
                "Error handling reconciliation of unit {}: {:#}",
                unit_name, e
            );
        }
    }
    let tracked_units = watched_units
        .read()
        .await
        .keys()
        .cloned()
        .collect::<Vec<_>>();
    prune_orphan_yamls(&tracked_units, fs, traefik_dir).context("pruning orphan unit yamls")
}

/// Removes generated files of units that are no longer tracked, e.g. removed or stripped of
/// their Traefik config while the daemon was not running.
fn prune_orphan_yamls<'a>(
    tracked_units: impl IntoIterator<Item = &'a String>,
    fs: &dyn FileSystem,
    traefik_dir: &Path,
) -> Result<()> {
    let tracked_paths = tracked_units
        .into_iter()
        .map(|unit| unit_yaml_path(unit, traefik_dir))
        .collect::<HashSet<_>>();
    for path in fs.list_files(traefik_dir)? {
        if path.extension().is_none_or(|extension| extension != "yml")
            || tracked_paths.contains(&path)
            || !fs
                .read_to_string(&path)
                .is_ok_and(|content| content.starts_with(GENERATED_MARKER))
        {
            continue;
        }
        if let Err(e) = fs.remove_file(&path) {
            error!("Error removing orphan {}: {:#}", path.display(), e);
            continue;
        }
        info!("Removed orphan {}", path.display());
    }
    Ok(())
}

fn unit_yaml_path(unit: &str, traefik_dir: &Path) -> PathBuf {
    traefik_dir.join(format!("{}.yml", sanitize_filename(unit)))
}

pub async fn process_service_change_messages(
    watched: UnitList,
    dbus: DBusContext<'static>,
    fs: Arc<dyn FileSystem>,
    traefik_dir: &Path,
) -> Result<(
    tokio::sync::mpsc::Sender<JobEvent>,
    tokio::task::JoinHandle<()>,
)> {
    let (tx, mut rx) = tokio::sync::mpsc::channel::<JobEvent>(100);
    let dbus = dbus.clone();
    let traefik_dir = traefik_dir.to_owned();
    let handle = tokio::spawn(async move {
        while let Some(job) = rx.recv().await {
            let result = if job.started {
                let unit_data = watched.read().await.get(&job.unit_name).cloned();
                let Some(unit_data) = unit_data else {
                    debug!(
                        "Not generating yaml for unit {}, it is not tracked.",
                        job.unit_name
                    );
                    continue;
                };
                handle_service_state_changed(&dbus, true, &unit_data, fs.as_ref(), &traefik_dir)
                    .await
            } else {
                // a unit dropped from tracking (e.g. lost its Traefik config) still needs its
                // yaml removed, so this does not depend on the unit data
                remove_unit_yaml(&job.unit_name, fs.as_ref(), &traefik_dir)
            };
            if let Err(e) = result {
                error!("Error handling service state change message: {:#}", e);
            } else {
                trace!("Message handled");
            }
        }
    });
    Ok((tx, handle))
}

pub async fn handle_service_state_changed(
    dbus: &DBusContext<'_>,
    started: bool,
    unit_data: &UnitData,
    fs: &dyn FileSystem,
    traefik_dir: &Path,
) -> Result<()> {
    trace!(
        "Handling start/stop for unit {}, started={started}",
        unit_data.name
    );
    if started {
        let lines = dbus
            .get_traefik_yaml_config_from_configuration_files(unit_data)
            .await?;
        let yaml_config = build_traefik_file_yaml(lines)?;
        write_unit_yaml(&unit_data.name, yaml_config, fs, traefik_dir)?;
    } else {
        remove_unit_yaml(&unit_data.name, fs, traefik_dir)?;
    }
    Ok(())
}

fn write_unit_yaml(
    unit: &str,
    yaml: String,
    fs: &dyn FileSystem,
    traefik_dir: &Path,
) -> Result<()> {
    let dest = unit_yaml_path(unit, traefik_dir);
    let content = format!("{GENERATED_MARKER}{yaml}");

    if fs.exists(&dest)
        && fs
            .read_to_string(&dest)
            .is_ok_and(|current| current == content)
    {
        trace!("Unit yaml for {} at {} is up to date", unit, dest.display());
        return Ok(());
    }

    trace!("Unit yaml for {} at {} is {yaml}", unit, dest.display());
    fs.write(&dest, &content)?;
    info!("Wrote {}", dest.display());
    Ok(())
}

fn remove_unit_yaml(unit: &str, fs: &dyn FileSystem, traefik_dir: &Path) -> Result<()> {
    let dest = unit_yaml_path(unit, traefik_dir);
    if !fs.exists(&dest) {
        return Ok(());
    }
    debug!("Removing unit yaml for {unit} from {}", dest.display());
    if fs.exists(&dest) {
        fs.remove_file(&dest)?;
    }
    info!("Removed {}", dest.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::*;
    use crate::infra::tests::MockFileSystem;
    use pretty_assertions::assert_eq;
    use serial_test::serial;
    use tempfile::TempDir;

    #[test]
    #[serial]
    fn test_write_unit_yaml_creates_file() {
        let temp_dir = TempDir::new().unwrap();
        let canonical_temp_path = temp_dir.path().canonicalize().unwrap();
        let fs = MockFileSystem::new();
        let result = write_unit_yaml("test.service", "foo".to_string(), &fs, &canonical_temp_path);
        assert!(result.is_ok());
        let yaml_path = canonical_temp_path.join("test.service.yml");
        assert!(
            fs.file_exists_in_memory(yaml_path.to_str().unwrap()),
            "YAML path: {}",
            yaml_path.display()
        );
        let content = fs.get_file_content(yaml_path.to_str().unwrap()).unwrap();
        assert_eq!(content, format!("{GENERATED_MARKER}foo"));
    }

    #[test]
    #[serial]
    fn test_write_unit_yaml_sanitizes_filename() {
        let temp_dir = TempDir::new().unwrap();
        let canonical_temp_path = temp_dir.path().canonicalize().unwrap();
        let fs = MockFileSystem::new();

        write_unit_yaml(
            "my@app!service.service",
            "foo".to_string(),
            &fs,
            &canonical_temp_path,
        )
        .unwrap();

        let yaml_path = canonical_temp_path.join("my_app_service.service.yml");
        assert!(fs.file_exists_in_memory(yaml_path.to_str().unwrap()));

        let content = fs.get_file_content(yaml_path.to_str().unwrap()).unwrap();
        assert_eq!(content, format!("{GENERATED_MARKER}foo"));
    }

    #[test]
    #[serial]
    fn test_write_unit_yaml_replaces_changed_content() {
        let fs = MockFileSystem::new();
        let traefik_dir = PathBuf::from("/traefik");
        fs.add_file("/traefik/test.service.yml", "old");
        write_unit_yaml("test.service", "new".to_string(), &fs, &traefik_dir).unwrap();
        assert_eq!(
            fs.get_file_content("/traefik/test.service.yml").unwrap(),
            format!("{GENERATED_MARKER}new")
        );
    }

    #[test]
    #[serial]
    fn test_write_unit_yaml_does_not_rewrite_unchanged_content() {
        let fs = MockFileSystem::new();
        let traefik_dir = PathBuf::from("/traefik");
        fs.add_file(
            "/traefik/test.service.yml",
            format!("{GENERATED_MARKER}same"),
        );
        write_unit_yaml("test.service", "same".to_string(), &fs, &traefik_dir).unwrap();
        assert_eq!(fs.write_count(), 0);
    }

    /// A unit whose D-Bus reads block until the test releases them.
    struct GatedSystemdUnit {
        tx_entered: std::sync::Mutex<Option<tokio::sync::oneshot::Sender<()>>>,
        rx_gate: tokio::sync::watch::Receiver<bool>,
    }

    #[async_trait::async_trait]
    impl crate::dbus::SystemdUnit for GatedSystemdUnit {
        async fn drop_in_paths(&self) -> Result<Vec<String>> {
            if let Some(tx_entered) = self.tx_entered.lock().unwrap().take() {
                tx_entered.send(()).unwrap();
            }
            self.rx_gate.clone().wait_for(|is_open| *is_open).await?;
            Ok(vec![])
        }

        async fn fragment_path(&self) -> Result<String> {
            Ok(String::new())
        }

        async fn active_state(&self) -> Result<String> {
            unimplemented!()
        }

        async fn receive_active_state_changed(
            &self,
        ) -> Result<std::pin::Pin<Box<dyn futures::Stream<Item = Result<String>> + Send>>> {
            unimplemented!()
        }
    }

    #[tokio::test]
    async fn test_processing_a_job_does_not_hold_the_units_lock_during_dbus_calls() {
        let (tx_entered, rx_entered) = tokio::sync::oneshot::channel();
        let (tx_gate, rx_gate) = tokio::sync::watch::channel(false);
        let unit = GatedSystemdUnit {
            tx_entered: std::sync::Mutex::new(Some(tx_entered)),
            rx_gate,
        };
        let watched = Arc::new(tokio::sync::RwLock::new(std::collections::HashMap::from([
            (
                "web.service".to_string(),
                Arc::new(UnitData::new_test("web.service", Box::new(unit))),
            ),
        ])));
        let fs = Arc::new(MockFileSystem::new());
        let dbus = DBusContext::new_test_context(
            Arc::new(crate::dbus::MockSystemdManager::new()),
            fs.clone(),
        );
        let (tx, handle) =
            process_service_change_messages(watched.clone(), dbus, fs, Path::new("/traefik"))
                .await
                .unwrap();

        tx.send(JobEvent {
            unit_name: "web.service".to_string(),
            started: true,
        })
        .await
        .unwrap();
        rx_entered.await.unwrap();
        let write_guard =
            tokio::time::timeout(tokio::time::Duration::from_millis(100), watched.write()).await;
        assert!(
            write_guard.is_ok(),
            "the units lock was held while waiting on D-Bus"
        );
        drop(write_guard);

        tx_gate.send(true).unwrap();
        drop(tx);
        handle.await.unwrap();
    }

    #[tokio::test]
    async fn test_repeated_start_jobs_rewrite_changed_labels() {
        // zbus only delivers the last ActiveState, so a quick restart is seen as active twice
        let fs = Arc::new(MockFileSystem::new());
        fs.add_file("/units/web.service", "[X-Traefik]\nLabel=traefik.a=1");
        let mut unit = crate::dbus::MockSystemdUnit::new();
        unit.expect_drop_in_paths().returning(|| Ok(vec![]));
        unit.expect_fragment_path()
            .returning(|| Ok("/units/web.service".to_string()));
        let watched = Arc::new(tokio::sync::RwLock::new(std::collections::HashMap::from([
            (
                "web.service".to_string(),
                Arc::new(UnitData::new_test("web.service", Box::new(unit))),
            ),
        ])));
        let dbus = DBusContext::new_test_context(
            Arc::new(crate::dbus::MockSystemdManager::new()),
            fs.clone(),
        );
        let (tx, handle) =
            process_service_change_messages(watched, dbus, fs.clone(), Path::new("/traefik"))
                .await
                .unwrap();
        let started = || JobEvent {
            unit_name: "web.service".to_string(),
            started: true,
        };

        tx.send(started()).await.unwrap();
        wait_for_file_content(
            &fs,
            "/traefik/web.service.yml",
            &format!("{GENERATED_MARKER}a: 1\n"),
        )
        .await;
        fs.add_file("/units/web.service", "[X-Traefik]\nLabel=traefik.b=2");
        tx.send(started()).await.unwrap();
        wait_for_file_content(
            &fs,
            "/traefik/web.service.yml",
            &format!("{GENERATED_MARKER}b: 2\n"),
        )
        .await;

        drop(tx);
        handle.await.unwrap();
    }

    async fn wait_for_file_content(fs: &MockFileSystem, path: &str, expected: &str) {
        let wait = async {
            while fs.get_file_content(path).as_deref() != Some(expected) {
                tokio::task::yield_now().await;
            }
        };
        tokio::time::timeout(tokio::time::Duration::from_millis(500), wait)
            .await
            .unwrap_or_else(|_| {
                panic!(
                    "{path} should contain {expected:?}, has {:?}",
                    fs.get_file_content(path)
                )
            });
    }

    fn unit_with_fragment(fragment_path: &'static str) -> Arc<UnitData> {
        let mut unit = crate::dbus::MockSystemdUnit::new();
        unit.expect_drop_in_paths().returning(|| Ok(vec![]));
        unit.expect_fragment_path()
            .returning(move || Ok(fragment_path.to_string()));
        let name = fragment_path.rsplit('/').next().unwrap();
        Arc::new(UnitData::new_test(name, Box::new(unit)))
    }

    fn watched_units(units: impl IntoIterator<Item = Arc<UnitData>>) -> UnitList {
        Arc::new(tokio::sync::RwLock::new(
            units
                .into_iter()
                .map(|unit| (unit.name.clone(), unit))
                .collect(),
        ))
    }

    #[tokio::test]
    async fn test_reconcile_writes_running_units_and_removes_stopped_ones() {
        let fs = Arc::new(MockFileSystem::new());
        fs.add_file("/units/running.service", "[X-Traefik]\nLabel=traefik.a=1");
        fs.add_file("/units/stopped.service", "[X-Traefik]\nLabel=traefik.b=2");
        fs.add_file("/units/unknown.service", "[X-Traefik]\nLabel=traefik.c=3");
        fs.add_file("/traefik/stopped.service.yml", GENERATED_MARKER);
        fs.add_file("/traefik/unknown.service.yml", GENERATED_MARKER);
        let mut mock_manager = crate::dbus::MockSystemdManager::new();
        mock_manager.expect_load_unit().returning(|name| {
            if name == "unknown.service" {
                Err(anyhow::anyhow!("no such unit"))
            } else {
                Ok(format!("/obj/{name}"))
            }
        });
        mock_manager.expect_get_unit().returning(|object_path| {
            let state = if object_path == "/obj/running.service" {
                "active"
            } else {
                "inactive"
            };
            let mut u = crate::dbus::MockSystemdUnit::new();
            u.expect_active_state()
                .returning(move || Ok(state.to_string()));
            Ok(Box::new(u))
        });
        let dbus = DBusContext::new_test_context(Arc::new(mock_manager), fs.clone());
        let watched = watched_units([
            unit_with_fragment("/units/running.service"),
            unit_with_fragment("/units/stopped.service"),
            unit_with_fragment("/units/unknown.service"),
        ]);

        reconcile(&dbus, &watched, fs.as_ref(), Path::new("/traefik"))
            .await
            .unwrap();

        assert_eq!(
            fs.get_file_content("/traefik/running.service.yml").unwrap(),
            format!("{GENERATED_MARKER}a: 1\n")
        );
        assert!(!fs.file_exists_in_memory("/traefik/stopped.service.yml"));
        assert!(
            !fs.file_exists_in_memory("/traefik/unknown.service.yml"),
            "a unit whose state can't be read is treated as stopped"
        );
    }

    #[tokio::test]
    async fn test_processing_skips_untracked_units_and_bad_labels_and_goes_on() {
        let fs = Arc::new(MockFileSystem::new());
        fs.add_file("/units/broken.service", "[X-Traefik]\nLabel=no_equals_sign");
        fs.add_file("/units/web.service", "[X-Traefik]\nLabel=traefik.a=1");
        let dbus = DBusContext::new_test_context(
            Arc::new(crate::dbus::MockSystemdManager::new()),
            fs.clone(),
        );
        let watched = watched_units([
            unit_with_fragment("/units/broken.service"),
            unit_with_fragment("/units/web.service"),
        ]);
        let (tx, handle) =
            process_service_change_messages(watched, dbus, fs.clone(), Path::new("/traefik"))
                .await
                .unwrap();

        for unit_name in ["untracked.service", "broken.service", "web.service"] {
            tx.send(JobEvent {
                unit_name: unit_name.to_string(),
                started: true,
            })
            .await
            .unwrap();
        }
        drop(tx);
        handle.await.unwrap();

        assert!(!fs.file_exists_in_memory("/traefik/untracked.service.yml"));
        assert!(!fs.file_exists_in_memory("/traefik/broken.service.yml"));
        assert_eq!(
            fs.get_file_content("/traefik/web.service.yml").unwrap(),
            format!("{GENERATED_MARKER}a: 1\n")
        );
    }

    #[tokio::test]
    async fn test_reconcile_removes_only_generated_orphans() {
        let fs = Arc::new(MockFileSystem::new());
        let orphan = format!("{GENERATED_MARKER}http: {{}}\n");
        fs.add_file("/traefik/gone.service.yml", orphan);
        fs.add_file("/traefik/handwritten.yml", "http: {}\n");
        fs.add_file("/traefik/notes.txt", GENERATED_MARKER);
        let dbus = DBusContext::new_test_context(
            Arc::new(crate::dbus::MockSystemdManager::new()),
            fs.clone(),
        );
        let watched = Arc::new(tokio::sync::RwLock::new(std::collections::HashMap::new()));

        reconcile(&dbus, &watched, fs.as_ref(), Path::new("/traefik"))
            .await
            .unwrap();

        assert!(!fs.file_exists_in_memory("/traefik/gone.service.yml"));
        assert!(fs.file_exists_in_memory("/traefik/handwritten.yml"));
        assert!(fs.file_exists_in_memory("/traefik/notes.txt"));
    }

    #[test]
    fn test_prune_orphan_yamls_keeps_tracked_units() {
        let fs = MockFileSystem::new();
        fs.add_file("/traefik/my_app.service.yml", GENERATED_MARKER);
        prune_orphan_yamls([&"my@app.service".to_string()], &fs, Path::new("/traefik")).unwrap();
        assert!(fs.file_exists_in_memory("/traefik/my_app.service.yml"));
    }

    #[tokio::test]
    async fn test_stop_job_removes_yaml_of_untracked_unit() {
        let fs = Arc::new(MockFileSystem::new());
        fs.add_file("/traefik/gone.service.yml", "old");
        let dbus = DBusContext::new_test_context(
            Arc::new(crate::dbus::MockSystemdManager::new()),
            fs.clone(),
        );
        let (tx, handle) = process_service_change_messages(
            Arc::new(tokio::sync::RwLock::new(std::collections::HashMap::new())),
            dbus,
            fs.clone(),
            Path::new("/traefik"),
        )
        .await
        .unwrap();

        tx.send(JobEvent {
            unit_name: "gone.service".to_string(),
            started: false,
        })
        .await
        .unwrap();
        drop(tx);
        handle.await.unwrap();

        assert!(!fs.file_exists_in_memory("/traefik/gone.service.yml"));
    }

    #[test]
    #[serial]
    fn test_remove_unit_yaml_deletes_file() {
        let temp_dir = TempDir::new().unwrap();
        let temp_path = temp_dir.path().to_str().unwrap().to_string();
        let fs = MockFileSystem::new();
        let yaml_path = temp_dir.path().join("test.service.yml");
        fs.add_file(yaml_path.to_str().unwrap(), "dummy content".to_string());
        assert!(
            fs.file_exists_in_memory(yaml_path.to_str().unwrap()),
            "File should exist before delete: {}",
            yaml_path.display()
        );

        let result = remove_unit_yaml("test.service", &fs, &PathBuf::from(temp_path));
        assert!(
            result.is_ok(),
            "remove_unit_yaml should succeed, error: {:?}",
            result
        );
        assert!(
            !fs.file_exists_in_memory(yaml_path.to_str().unwrap()),
            "YAML file should be deleted at {}",
            yaml_path.display()
        );
    }

    #[test]
    #[serial]
    fn test_remove_unit_yaml_nonexistent_file() {
        let temp_dir = TempDir::new().unwrap();
        let canonical_temp_path = temp_dir.path().canonicalize().unwrap();
        let fs = MockFileSystem::new();
        let result = remove_unit_yaml("nonexistent.service", &fs, &canonical_temp_path);
        assert!(result.is_ok());
    }

    #[test]
    #[serial]
    fn test_remove_unit_yaml_sanitizes_filename() {
        let temp_dir = TempDir::new().unwrap();
        let canonical_temp_path = temp_dir.path().canonicalize().unwrap();
        let fs = MockFileSystem::new();
        let yaml_path = canonical_temp_path.join("my_app_service.service.yml");
        fs.add_file(yaml_path.to_str().unwrap(), "dummy content".to_string());
        assert!(fs.file_exists_in_memory(yaml_path.to_str().unwrap()));
        let result = remove_unit_yaml("my@app!service.service", &fs, &canonical_temp_path);
        assert!(result.is_ok());
        assert!(!fs.file_exists_in_memory(yaml_path.to_str().unwrap()));
    }
}
