//! # D-Bus interface proxy for: `org.freedesktop.systemd1.Manager`
//!
//! Generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data
//! (`Interface '/org/freedesktop/systemd1' from service 'org.freedesktop.systemd1' on system bus`),
//! then trimmed to the members this application uses. To add one, regenerate with
//! `zbus-xmlgen system org.freedesktop.systemd1 /org/freedesktop/systemd1` and copy it over.
use zbus::proxy;
#[proxy(
    interface = "org.freedesktop.systemd1.Manager",
    default_service = "org.freedesktop.systemd1",
    default_path = "/org/freedesktop/systemd1"
)]
pub trait Manager {
    /// ListUnits method
    #[allow(clippy::type_complexity)]
    fn list_units(
        &self,
    ) -> zbus::Result<
        Vec<(
            String,
            String,
            String,
            String,
            String,
            String,
            zbus::zvariant::OwnedObjectPath,
            u32,
            String,
            zbus::zvariant::OwnedObjectPath,
        )>,
    >;

    /// LoadUnit method
    fn load_unit(&self, name: &str) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Subscribe method
    fn subscribe(&self) -> zbus::Result<()>;

    /// Reloading signal
    #[zbus(signal)]
    fn reloading(&self, active: bool) -> zbus::Result<()>;

    /// UnitNew signal
    #[zbus(signal)]
    fn unit_new(&self, id: &str, unit: zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;
}
