//! # D-Bus interface proxy for: `org.freedesktop.systemd1.Unit`
//!
//! Generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data
//! (`Interface '/org/freedesktop/systemd1/unit/sleep_2eservice' from service
//! 'org.freedesktop.systemd1' on system bus`), then trimmed to the members this application uses.
//! To add one, regenerate with
//! `zbus-xmlgen system org.freedesktop.systemd1 /org/freedesktop/systemd1/unit/sleep_2eservice`
//! and copy it over, keeping the changes to the file path properties below.
use zbus::proxy;
#[proxy(
    interface = "org.freedesktop.systemd1.Unit",
    default_service = "org.freedesktop.systemd1"
)]
pub trait Unit {
    /// ActiveState property
    #[zbus(property)]
    fn active_state(&self) -> zbus::Result<String>;

    /// DropInPaths property
    // systemd declares it `const`, but it changes on daemon-reload (on NixOS every rebuild
    // moves drop-ins to a new store path), so it is never cached.
    #[zbus(property(emits_changed_signal = "false"))]
    fn drop_in_paths(&self) -> zbus::Result<Vec<String>>;

    /// FragmentPath property
    // systemd declares it `const`, but it changes on daemon-reload (on NixOS every rebuild
    // moves drop-ins to a new store path), so it is never cached.
    #[zbus(property(emits_changed_signal = "false"))]
    fn fragment_path(&self) -> zbus::Result<String>;
}
